language: python

service:
  - postgresql
python:
# only test against versions: 
  - '3.4'
  
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

before_script:

  - cd tests
  - psql -c 'create database travis;' -U postgres
script: 
  - pytest
  - pytest --cov=.
  
after_success:
- coveralls  