FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AndelaDiary

Polls is a simple API allowing consumers to view polls and vote in them.
## Questions Collection [/api/v2]

## Register Collection [/api/v2/auth/signup]

When an interested  person may register in the application.
The system will prompt a user to register with, Full_name, username, email, password, confirm_password

### Registration [POST]
+ Request (application/json)
    + Attributes 
        - id: `1` (number) - User id
        - full_name: `wagole musa` (string) - Full names
        - username: `refuge` (string) - Username
        - email: `homiemusa@gmail.com` (string) email Address
        - password: `wise@12` (string) Password
        - confirm_password: `wise@12` (string) Password Confirmation

+ Response 200 (application/json)

## Login Collection [/api/v2/auth/login]
After a user is successfuly Registered, He or she con login with username and password 

### Login[POST]

+ Request 200 (application/json)
    + Attributes
        - username: `refuge` (string)
        - password: `wise@12` (string)